language: python
python:
  - "3.5"

branches:
  only:
    - master

install:
  - pip install coveralls codecov nox

script: nox --session "test"

after_success:
  - coveralls
  - codecov

notifications:
  email: false
